test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -22,54 +22,54 @@ executors:
 
 
 jobs:
-  ensure_formatting:
-    docker:
-      - image: cimg/python:3.12
-    working_directory: ~/repo
-    steps:
-      - checkout
-      - run: sudo apt-get update -qq && sudo apt install curl gettext-base
-      - run:
-          name: install dependencies
-          command: pip install -r ci-requirements.txt --user
-      - run:
-          name: run isort check
-          command: isort --profile black --check .
-      - run:
-          name: run black check
-          command: black --check .
-      - slack/notify:
-          event: fail
-          template: basic_fail_1
-  base_linter:
-    docker:
-      - image: alpine/flake8:7.3.0
-    working_directory: ~/repo
-    steps:
-      - checkout
-      - run: apk update && apk upgrade && apk --no-cache add curl gettext
-      - run:
-          name: flake8
-          command: flake8 --ignore=E,W ~/repo
-      - slack/notify:
-          event: fail
-          template: basic_fail_1
-  linter:
-    docker:
-      - image: cimg/python:3.12
-    working_directory: ~/repo
-    steps:
-      - checkout
-      - run: sudo apt-get update -qq && sudo apt install curl gettext-base
-      - run:
-          name: install dependencies
-          command: pip install -r ./shared/pylint_plugins/check_stix_plugin/requirements.txt
-      - run:
-          name: pylint
-          command: cd ./shared/pylint_plugins/check_stix_plugin && PYTHONPATH=. python -m pylint ../../../ --disable=all --enable=no_generated_id_stix,no-value-for-parameter,unused-import --load-plugins linter_stix_id_generator
-      - slack/notify:
-          event: fail
-          template: basic_fail_1
+#  ensure_formatting:
+#    docker:
+#      - image: cimg/python:3.12
+#    working_directory: ~/repo
+#    steps:
+#      - checkout
+#      - run: sudo apt-get update -qq && sudo apt install curl gettext-base
+#      - run:
+#          name: install dependencies
+#          command: pip install -r ci-requirements.txt --user
+#      - run:
+#          name: run isort check
+#          command: isort --profile black --check .
+#      - run:
+#          name: run black check
+#          command: black --check .
+#      - slack/notify:
+#          event: fail
+#          template: basic_fail_1
+#  base_linter:
+#    docker:
+#      - image: alpine/flake8:7.3.0
+#    working_directory: ~/repo
+#    steps:
+#      - checkout
+#      - run: apk update && apk upgrade && apk --no-cache add curl gettext
+#      - run:
+#          name: flake8
+#          command: flake8 --ignore=E,W ~/repo
+#      - slack/notify:
+#          event: fail
+#          template: basic_fail_1
+#  linter:
+#    docker:
+#      - image: cimg/python:3.12
+#    working_directory: ~/repo
+#    steps:
+#      - checkout
+#      - run: sudo apt-get update -qq && sudo apt install curl gettext-base
+#      - run:
+#          name: install dependencies
+#          command: pip install -r ./shared/pylint_plugins/check_stix_plugin/requirements.txt
+#      - run:
+#          name: pylint
+#          command: cd ./shared/pylint_plugins/check_stix_plugin && PYTHONPATH=. python -m pylint ../../../ --disable=all --enable=no_generated_id_stix,no-value-for-parameter,unused-import --load-plugins linter_stix_id_generator
+#      - slack/notify:
+#          event: fail
+#          template: basic_fail_1
   build_manifest:
     docker:
       - image: cimg/python:3.12
@@ -114,95 +114,98 @@ jobs:
               echo "Skipping steps due to [ci build-manifest] flag."
               exit 0
             fi
-  test:
-    docker:
-      - image: cimg/python:3.11
-    working_directory: ~/repo
-    parallelism: 4
-    steps:
-      - checkout
-      - run: | 
-          sudo apt-get update -qq 
-          sudo apt install -y \
-            curl \
-            gettext-base \
-            libcairo2-dev libpango1.0-dev  # for internal-export-file/export-report-pdf tests (weasyprint)
-      - run:
-          name: install dependencies
-          command: pip install -r ci-requirements.txt --user
-      - run:
-          name: Run tests
-          command: |
-            set -euo pipefail
-            circleci tests glob "**/test-requirements.txt" \
-              | circleci tests run \
-                  --split-by=timings \
-                  --command="xargs bash run_test.sh"
-        # Save JUnit so CircleCI can show pass/fail per connector and build timings history
-      - store_test_results:
-          path: test_outputs
-
-      # Save logs/reports as downloadable artifacts
-      - store_artifacts:
-          path: test_outputs
-  build:
-    parameters:
-      ci_executor:
-        type: executor
-        description: Executor to use for this job.
-        default: ci_environment
-    executor: << parameters.ci_executor >>
-    steps:
-      - checkout
-      - run:
-          name: Install dependencies
-          command: pip install -r .circleci/scripts/requirements.txt
-      - run:
-          name: Execute Python Script
-          command: python .circleci/scripts/generate_ci.py
-      - continuation/continue:
-          configuration_path: dynamic.yml
-      - slack/notify:
-          event: fail
-          template: basic_fail_1
-  notify:
-    parameters:
-      notification_executor:
-        type: executor
-        description: Executor to use for this job.
-        default: ci_notifications
-    executor: << parameters.notification_executor >>
-    steps:
-      - run: sudo apt-get update -qq && sudo apt install curl gettext-base
-      - slack/notify:
-          event: pass
-          template: basic_success_1
+#  test:
+#    docker:
+#      - image: cimg/python:3.11
+#    working_directory: ~/repo
+#    parallelism: 4
+#    steps:
+#      - checkout
+#      - run: |
+#          sudo apt-get update -qq
+#          sudo apt install -y \
+#            curl \
+#            gettext-base \
+#            libcairo2-dev libpango1.0-dev  # for internal-export-file/export-report-pdf tests (weasyprint)
+#      - run:
+#          name: install dependencies
+#          command: pip install -r ci-requirements.txt --user
+#      - run:
+#          name: Run tests
+#          command: |
+#            set -euo pipefail
+#            circleci tests glob "**/test-requirements.txt" \
+#              | circleci tests run \
+#                  --split-by=timings \
+#                  --command="xargs bash run_test.sh"
+#        # Save JUnit so CircleCI can show pass/fail per connector and build timings history
+#      - store_test_results:
+#          path: test_outputs
+#
+#      # Save logs/reports as downloadable artifacts
+#      - store_artifacts:
+#          path: test_outputs
+#  build:
+#    parameters:
+#      ci_executor:
+#        type: executor
+#        description: Executor to use for this job.
+#        default: ci_environment
+#    executor: << parameters.ci_executor >>
+#    steps:
+#      - checkout
+#      - run:
+#          name: Install dependencies
+#          command: pip install -r .circleci/scripts/requirements.txt
+#      - run:
+#          name: Execute Python Script
+#          command: python .circleci/scripts/generate_ci.py
+#      - continuation/continue:
+#          configuration_path: dynamic.yml
+#      - slack/notify:
+#          event: fail
+#          template: basic_fail_1
+#  notify:
+#    parameters:
+#      notification_executor:
+#        type: executor
+#        description: Executor to use for this job.
+#        default: ci_notifications
+#    executor: << parameters.notification_executor >>
+#    steps:
+#      - run: sudo apt-get update -qq && sudo apt install curl gettext-base
+#      - slack/notify:
+#          event: pass
+#          template: basic_success_1
 
 workflows:
   connectors:
     jobs:
-      - ensure_formatting:
-          filters:
-              tags:
-                only: /.*/
-      - base_linter:
-          filters:
-            tags:
-              only: /.*/
-      - linter:
-          filters:
-            tags:
-              only: /.*/
-      - test:
-          filters:
-            tags:
-              only: /.*/
+#      - ensure_formatting:
+#          filters:
+#              tags:
+#                only: /.*/
+#      - base_linter:
+#          filters:
+#            tags:
+#              only: /.*/
+#      - linter:
+#          filters:
+#            tags:
+#              only: /.*/
+#      - test:
+#          filters:
+#            tags:
+#              only: /.*/
       - build_manifest:
-          requires:
-            - ensure_formatting
-            - base_linter
-            - linter
-            - test
+          filters:
+            tags:
+              only: /.*/
+#          requires:
+#            - ensure_formatting
+#            - base_linter
+#            - linter
+#            - test
       - build:
           name: "build_release"
           ci_executor:
